package com.pensionrun.entity.log;
// Generated 2016. 6. 14 오후 3:40:00 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogScheduler generated by hbm2java
 */
@Entity
@Table(name = "_log_scheduler", catalog = "PensionRun")
public class LogScheduler implements java.io.Serializable {

	private Integer idfLogScheduler;
	private char type;
	private Date scheduledDate;
	private int appliedCount;

	public LogScheduler() {
	}

	public LogScheduler(char type, Date scheduledDate, int appliedCount) {
		this.type = type;
		this.scheduledDate = scheduledDate;
		this.appliedCount = appliedCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_log_scheduler", unique = true, nullable = false)
	public Integer getIdfLogScheduler() {
		return this.idfLogScheduler;
	}

	public void setIdfLogScheduler(Integer idfLogScheduler) {
		this.idfLogScheduler = idfLogScheduler;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduled_date", nullable = false, length = 19)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Column(name = "applied_count", nullable = false)
	public int getAppliedCount() {
		return this.appliedCount;
	}

	public void setAppliedCount(int appliedCount) {
		this.appliedCount = appliedCount;
	}

}
