package com.pensionrun.entity;
// Generated 2016. 5. 19 오후 11:24:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountPensionId generated by hbm2java
 */
@Embeddable
public class AccountPensionId implements java.io.Serializable {

	private int idfAccount;
	private int idfPension;

	public AccountPensionId() {
	}

	public AccountPensionId(int idfAccount, int idfPension) {
		this.idfAccount = idfAccount;
		this.idfPension = idfPension;
	}

	@Column(name = "idf_account", nullable = false)
	public int getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(int idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "idf_pension", nullable = false)
	public int getIdfPension() {
		return this.idfPension;
	}

	public void setIdfPension(int idfPension) {
		this.idfPension = idfPension;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountPensionId))
			return false;
		AccountPensionId castOther = (AccountPensionId) other;

		return (this.getIdfAccount() == castOther.getIdfAccount())
				&& (this.getIdfPension() == castOther.getIdfPension());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfAccount();
		result = 37 * result + this.getIdfPension();
		return result;
	}

}
