package com.pensionrun.entity;
// Generated 2016. 5. 19 오후 11:24:48 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "PensionRun", uniqueConstraints = @UniqueConstraint(columnNames = "userid"))
public class Account implements java.io.Serializable {

	private Integer idfAccount;
	private String userid;
	private String password;
	private String name;
	private String email;
	private char emailReception;
	private float coin;
	private String mobile;
	private String urlImageProfile;
	private char typeOs;
	private char typeServicePlatform;
	private char state;
	private Date regDate;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<AccountPension> accountPensions = new HashSet<AccountPension>(0);

	public Account() {
	}

	public Account(String userid, String password, String name, float coin, String mobile, char typeOs,
			char typeServicePlatform, char state, Date regDate) {
		this.userid = userid;
		this.password = password;
		this.name = name;
		this.coin = coin;
		this.mobile = mobile;
		this.typeOs = typeOs;
		this.typeServicePlatform = typeServicePlatform;
		this.state = state;
		this.regDate = regDate;
	}

	public Account(String userid, String password, String name, String email, char emailReception, float coin,
			String mobile, String urlImageProfile, char typeOs, char typeServicePlatform, char state, Date regDate,
			Set<Order> orders, Set<Review> reviews, Set<AccountPension> accountPensions) {
		this.userid = userid;
		this.password = password;
		this.name = name;
		this.email = email;
		this.emailReception = emailReception;
		this.coin = coin;
		this.mobile = mobile;
		this.urlImageProfile = urlImageProfile;
		this.typeOs = typeOs;
		this.typeServicePlatform = typeServicePlatform;
		this.state = state;
		this.regDate = regDate;
		this.orders = orders;
		this.reviews = reviews;
		this.accountPensions = accountPensions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_account", unique = true, nullable = false)
	public Integer getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(Integer idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "userid", unique = true, nullable = false, length = 50)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "email_reception", nullable = false, length = 1)
	public char getEmailReception() {
		return this.emailReception;
	}

	public void setEmailReception(char emailReception) {
		this.emailReception = emailReception;
	}

	@Column(name = "coin", nullable = false, precision = 12, scale = 0)
	public float getCoin() {
		return this.coin;
	}

	public void setCoin(float coin) {
		this.coin = coin;
	}

	@Column(name = "mobile", nullable = false, length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "url_image_profile", length = 500)
	public String getUrlImageProfile() {
		return this.urlImageProfile;
	}

	public void setUrlImageProfile(String urlImageProfile) {
		this.urlImageProfile = urlImageProfile;
	}

	@Column(name = "type_os", nullable = false, length = 1)
	public char getTypeOs() {
		return this.typeOs;
	}

	public void setTypeOs(char typeOs) {
		this.typeOs = typeOs;
	}

	@Column(name = "type_service_platform", nullable = false, length = 1)
	public char getTypeServicePlatform() {
		return this.typeServicePlatform;
	}

	public void setTypeServicePlatform(char typeServicePlatform) {
		this.typeServicePlatform = typeServicePlatform;
	}

	@Column(name = "state", nullable = false, length = 1)
	public char getState() {
		return this.state;
	}

	public void setState(char state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<AccountPension> getAccountPensions() {
		return this.accountPensions;
	}

	public void setAccountPensions(Set<AccountPension> accountPensions) {
		this.accountPensions = accountPensions;
	}

	

}
