package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Amenity generated by hbm2java
 */
@Entity
@Table(name = "amenity", catalog = "PensionRun")
public class Amenity implements java.io.Serializable {

	private Integer idfAmenity;
	private String name;
	private Byte priority;
	private Date regDate;
	private Set<RoomAmenity> roomAmenities = new HashSet<RoomAmenity>(0);

	public Amenity() {
	}

	public Amenity(String name, Date regDate) {
		this.name = name;
		this.regDate = regDate;
	}

	public Amenity(String name, Byte priority, Date regDate, Set<RoomAmenity> roomAmenities) {
		this.name = name;
		this.priority = priority;
		this.regDate = regDate;
		this.roomAmenities = roomAmenities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_amenity", unique = true, nullable = false)
	public Integer getIdfAmenity() {
		return this.idfAmenity;
	}

	public void setIdfAmenity(Integer idfAmenity) {
		this.idfAmenity = idfAmenity;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amenity")
	public Set<RoomAmenity> getRoomAmenities() {
		return this.roomAmenities;
	}

	public void setRoomAmenities(Set<RoomAmenity> roomAmenities) {
		this.roomAmenities = roomAmenities;
	}

}
