package com.pensionrun.entity;
// Generated 2016. 6. 8 오전 11:35:54 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppInfoId generated by hbm2java
 */
@Embeddable
public class AppInfoId implements java.io.Serializable {

	private String version;
	private char typeOs;

	public AppInfoId() {
	}

	public AppInfoId(String version, char typeOs) {
		this.version = version;
		this.typeOs = typeOs;
	}

	@Column(name = "version_", nullable = false, length = 15)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "type_os", nullable = false, length = 1)
	public char getTypeOs() {
		return this.typeOs;
	}

	public void setTypeOs(char typeOs) {
		this.typeOs = typeOs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppInfoId))
			return false;
		AppInfoId castOther = (AppInfoId) other;

		return ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
				&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
				&& (this.getTypeOs() == castOther.getTypeOs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + this.getTypeOs();
		return result;
	}

}
