package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Area2 generated by hbm2java
 */
@Entity
@Table(name = "area2", catalog = "PensionRun")
public class Area2 implements java.io.Serializable {

	private Integer idfArea2;
	private Area1 area1;
	private String name;
	private Date regDate;
	private Set<Pension> pensions = new HashSet<Pension>(0);

	public Area2() {
	}

	public Area2(Area1 area1, String name, Date regDate) {
		this.area1 = area1;
		this.name = name;
		this.regDate = regDate;
	}

	public Area2(Area1 area1, String name, Date regDate, Set<Pension> pensions) {
		this.area1 = area1;
		this.name = name;
		this.regDate = regDate;
		this.pensions = pensions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_area2", unique = true, nullable = false)
	public Integer getIdfArea2() {
		return this.idfArea2;
	}

	public void setIdfArea2(Integer idfArea2) {
		this.idfArea2 = idfArea2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_area1", nullable = false)
	public Area1 getArea1() {
		return this.area1;
	}

	public void setArea1(Area1 area1) {
		this.area1 = area1;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area2")
	public Set<Pension> getPensions() {
		return this.pensions;
	}

	public void setPensions(Set<Pension> pensions) {
		this.pensions = pensions;
	}

}
