package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Area1 generated by hbm2java
 */
@Entity
@Table(name = "area1", catalog = "PensionRun")
public class Area1 implements java.io.Serializable {

	private Integer idfArea1;
	private String name;
	private Date regDate;
	private Set<Area2> area2s = new HashSet<Area2>(0);

	public Area1() {
	}

	public Area1(String name, Date regDate) {
		this.name = name;
		this.regDate = regDate;
	}

	public Area1(String name, Date regDate, Set<Area2> area2s) {
		this.name = name;
		this.regDate = regDate;
		this.area2s = area2s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_area1", unique = true, nullable = false)
	public Integer getIdfArea1() {
		return this.idfArea1;
	}

	public void setIdfArea1(Integer idfArea1) {
		this.idfArea1 = idfArea1;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area1")
	public Set<Area2> getArea2s() {
		return this.area2s;
	}

	public void setArea2s(Set<Area2> area2s) {
		this.area2s = area2s;
	}

	@Override
	public String toString() {
		return "Area1 [idfArea1=" + idfArea1 + ", name=" + name + ", regDate=" + regDate + ", area2s=" + area2s + "]";
	}

}
