package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "PensionRun")
public class Event implements java.io.Serializable {

	private Integer idfEvent;
	private String title;
	private String dateStart;
	private String dateEnd;
	private String image;
	private String urlContent;
	private String urlResult;
	private Date regDate;

	public Event() {
	}

	public Event(String title, String dateStart, String dateEnd, String image, String urlContent, String urlResult,
			Date regDate) {
		this.title = title;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.image = image;
		this.urlContent = urlContent;
		this.urlResult = urlResult;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_event", unique = true, nullable = false)
	public Integer getIdfEvent() {
		return this.idfEvent;
	}

	public void setIdfEvent(Integer idfEvent) {
		this.idfEvent = idfEvent;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "date_start", nullable = false, length = 10)
	public String getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(String dateStart) {
		this.dateStart = dateStart;
	}

	@Column(name = "date_end", nullable = false, length = 10)
	public String getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(String dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "image", nullable = false, length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "url_content", nullable = false, length = 45)
	public String getUrlContent() {
		return this.urlContent;
	}

	public void setUrlContent(String urlContent) {
		this.urlContent = urlContent;
	}

	@Column(name = "url_result", nullable = false, length = 45)
	public String getUrlResult() {
		return this.urlResult;
	}

	public void setUrlResult(String urlResult) {
		this.urlResult = urlResult;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
