package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name = "facility", catalog = "PensionRun")
public class Facility implements java.io.Serializable {

	private Integer idfFacility;
	private String name;
	private Byte priority;
	private Date regDate;
	private Set<PensionFacility> pensionFacilities = new HashSet<PensionFacility>(0);

	public Facility() {
	}

	public Facility(String name, Date regDate) {
		this.name = name;
		this.regDate = regDate;
	}

	public Facility(String name, Byte priority, Date regDate, Set<PensionFacility> pensionFacilities) {
		this.name = name;
		this.priority = priority;
		this.regDate = regDate;
		this.pensionFacilities = pensionFacilities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_facility", unique = true, nullable = false)
	public Integer getIdfFacility() {
		return this.idfFacility;
	}

	public void setIdfFacility(Integer idfFacility) {
		this.idfFacility = idfFacility;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set<PensionFacility> getPensionFacilities() {
		return this.pensionFacilities;
	}

	public void setPensionFacilities(Set<PensionFacility> pensionFacilities) {
		this.pensionFacilities = pensionFacilities;
	}

}
