package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name = "faq", catalog = "PensionRun")
public class Faq implements java.io.Serializable {

	private Integer idfFaq;
	private String subject;
	private String content;
	private Date regDate;

	public Faq() {
	}

	public Faq(String subject, String content) {
		this.subject = subject;
		this.content = content;
	}

	public Faq(String subject, String content, Date regDate) {
		this.subject = subject;
		this.content = content;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_faq", unique = true, nullable = false)
	public Integer getIdfFaq() {
		return this.idfFaq;
	}

	public void setIdfFaq(Integer idfFaq) {
		this.idfFaq = idfFaq;
	}

	@Column(name = "subject", nullable = false, length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
