package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.pensionrun.entity.Admin;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name = "notice", catalog = "PensionRun")
public class Notice implements java.io.Serializable {

	private Integer idfNotice;
	private Admin admin;
	private String subject;
	private String content;
	private Date regDate;

	public Notice() {
	}

	public Notice(Admin admin, String subject, String content, Date regDate) {
		this.admin = admin;
		this.subject = subject;
		this.content = content;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_notice", unique = true, nullable = false)
	public Integer getIdfNotice() {
		return this.idfNotice;
	}

	public void setIdfNotice(Integer idfNotice) {
		this.idfNotice = idfNotice;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_admin", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "subject", nullable = false, length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19,insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Override
	public String toString() {
		return "Notice [idfNotice=" + idfNotice + ", subject=" + subject + ", content=" + content + ", regDate="
				+ regDate + "]";
	}
	
}
