package com.pensionrun.entity;
// Generated 2016. 5. 27 오전 10:36:21 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PaymentCancelCard generated by hbm2java
 */
@Entity
@Table(name = "payment_cancel_card", catalog = "PensionRun")
public class PaymentCancelCard implements java.io.Serializable {

	private String idfPayment;
	private Payment payment;
	private String receiveDate;
	private String proceedDate;
	private Float refundAmount;
	private Date regDate;

	public PaymentCancelCard() {
	}

	public PaymentCancelCard(Payment payment, String receiveDate, Date regDate) {
		this.payment = payment;
		this.receiveDate = receiveDate;
		this.regDate = regDate;
	}

	public PaymentCancelCard(Payment payment, String receiveDate, String proceedDate, Float refundAmount,
			Date regDate) {
		this.payment = payment;
		this.receiveDate = receiveDate;
		this.proceedDate = proceedDate;
		this.refundAmount = refundAmount;
		this.regDate = regDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "payment"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idf_payment", unique = true, nullable = false, length = 30)
	public String getIdfPayment() {
		return this.idfPayment;
	}

	public void setIdfPayment(String idfPayment) {
		this.idfPayment = idfPayment;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "receive_date", nullable = false, length = 16)
	public String getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(String receiveDate) {
		this.receiveDate = receiveDate;
	}

	@Column(name = "proceed_date", length = 16)
	public String getProceedDate() {
		return this.proceedDate;
	}

	public void setProceedDate(String proceedDate) {
		this.proceedDate = proceedDate;
	}

	@Column(name = "refund_amount", precision = 12, scale = 0)
	public Float getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(Float refundAmount) {
		this.refundAmount = refundAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
