package com.pensionrun.entity;
// Generated 2016. 5. 27 오전 10:36:21 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PaymentCard generated by hbm2java
 */
@Entity
@Table(name = "payment_card", catalog = "PensionRun")
public class PaymentCard implements java.io.Serializable {

	private String idfPayment;
	private Payment payment;
	private String number;
	private String code;
	private String name;
	private String month;
	private String authCode;
	private String authDate;

	public PaymentCard() {
	}

	public PaymentCard(Payment payment, String number, String code, String name, String month, String authCode,
			String authDate) {
		this.payment = payment;
		this.number = number;
		this.code = code;
		this.name = name;
		this.month = month;
		this.authCode = authCode;
		this.authDate = authDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "payment"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idf_payment", unique = true, nullable = false, length = 30)
	public String getIdfPayment() {
		return this.idfPayment;
	}

	public void setIdfPayment(String idfPayment) {
		this.idfPayment = idfPayment;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "number", nullable = false, length = 16)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "code", nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "month", nullable = false, length = 2)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "auth_code", nullable = false, length = 20)
	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	@Column(name = "auth_date", nullable = false, length = 20)
	public String getAuthDate() {
		return this.authDate;
	}

	public void setAuthDate(String authDate) {
		this.authDate = authDate;
	}

}
