package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PensionThemeId generated by hbm2java
 */
@Embeddable
public class PensionThemeId implements java.io.Serializable {

	private int idfTheme;
	private int idfPension;

	public PensionThemeId() {
	}

	public PensionThemeId(int idfTheme, int idfPension) {
		this.idfTheme = idfTheme;
		this.idfPension = idfPension;
	}

	@Column(name = "idf_theme", nullable = false)
	public int getIdfTheme() {
		return this.idfTheme;
	}

	public void setIdfTheme(int idfTheme) {
		this.idfTheme = idfTheme;
	}

	@Column(name = "idf_pension", nullable = false)
	public int getIdfPension() {
		return this.idfPension;
	}

	public void setIdfPension(int idfPension) {
		this.idfPension = idfPension;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PensionThemeId))
			return false;
		PensionThemeId castOther = (PensionThemeId) other;

		return (this.getIdfTheme() == castOther.getIdfTheme()) && (this.getIdfPension() == castOther.getIdfPension());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfTheme();
		result = 37 * result + this.getIdfPension();
		return result;
	}

}
