package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PensionTheme generated by hbm2java
 */
@Entity
@Table(name = "pension_theme", catalog = "PensionRun")
public class PensionTheme implements java.io.Serializable {

	private PensionThemeId id;
	private Pension pension;
	private Theme theme;
	private Date regDate;

	public PensionTheme() {
	}

	public PensionTheme(PensionThemeId id, Pension pension, Theme theme, Date regDate) {
		this.id = id;
		this.pension = pension;
		this.theme = theme;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idfTheme", column = @Column(name = "idf_theme", nullable = false)),
			@AttributeOverride(name = "idfPension", column = @Column(name = "idf_pension", nullable = false)) })
	public PensionThemeId getId() {
		return this.id;
	}

	public void setId(PensionThemeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_pension", nullable = false, insertable = false, updatable = false)
	public Pension getPension() {
		return this.pension;
	}

	public void setPension(Pension pension) {
		this.pension = pension;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_theme", nullable = false, insertable = false, updatable = false)
	public Theme getTheme() {
		return this.theme;
	}

	public void setTheme(Theme theme) {
		this.theme = theme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
