package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PensionProvideId generated by hbm2java
 */
@Embeddable
public class PensionProvideId implements java.io.Serializable {

	private int idfPension;
	private int idfProvide;

	public PensionProvideId() {
	}

	public PensionProvideId(int idfPension, int idfProvide) {
		this.idfPension = idfPension;
		this.idfProvide = idfProvide;
	}

	@Column(name = "idf_pension", nullable = false)
	public int getIdfPension() {
		return this.idfPension;
	}

	public void setIdfPension(int idfPension) {
		this.idfPension = idfPension;
	}

	@Column(name = "idf_provide", nullable = false)
	public int getIdfProvide() {
		return this.idfProvide;
	}

	public void setIdfProvide(int idfProvide) {
		this.idfProvide = idfProvide;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PensionProvideId))
			return false;
		PensionProvideId castOther = (PensionProvideId) other;

		return (this.getIdfPension() == castOther.getIdfPension())
				&& (this.getIdfProvide() == castOther.getIdfProvide());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfPension();
		result = 37 * result + this.getIdfProvide();
		return result;
	}

}
