package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PensionImage generated by hbm2java
 */
@Entity
@Table(name = "pension_image", catalog = "PensionRun")
public class PensionImage implements java.io.Serializable {

	private Integer idfPensionImage;
	private Pension pension;
	private String image;
	private Byte priority;
	private Date regDate;

	public PensionImage() {
	}

	public PensionImage(Pension pension) {
		this.pension = pension;
	}

	public PensionImage(Pension pension, String image, Byte priority, Date regDate) {
		this.pension = pension;
		this.image = image;
		this.priority = priority;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_pension_image", unique = true, nullable = false)
	public Integer getIdfPensionImage() {
		return this.idfPensionImage;
	}

	public void setIdfPensionImage(Integer idfPensionImage) {
		this.idfPensionImage = idfPensionImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_pension", nullable = false)
	public Pension getPension() {
		return this.pension;
	}

	public void setPension(Pension pension) {
		this.pension = pension;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
