package com.pensionrun.entity;
// Generated 2016. 6. 16 오전 11:11:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PensionInquiry generated by hbm2java
 */
@Entity
@Table(name = "pension_inquiry", catalog = "PensionRun")
public class PensionInquiry implements java.io.Serializable {

	private Integer idfPensionInquiry;
	private String name;
	private String area;
	private String phone;
	private Date regDate;

	public PensionInquiry() {
	}

	public PensionInquiry(String name, String area, String phone, Date regDate) {
		this.name = name;
		this.area = area;
		this.phone = phone;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_pension_inquiry", unique = true, nullable = false)
	public Integer getIdfPensionInquiry() {
		return this.idfPensionInquiry;
	}

	public void setIdfPensionInquiry(Integer idfPensionInquiry) {
		this.idfPensionInquiry = idfPensionInquiry;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "area", nullable = false, length = 45)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "phone", nullable = false, length = 13)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
