package com.pensionrun.entity;
// Generated 2016. 5. 17 오전 10:44:27 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pension generated by hbm2java
 */
@Entity
@Table(name = "pension", catalog = "PensionRun")
public class Pension implements java.io.Serializable {

	private Integer idfPension;
	private Area2 area2;
	private String idfProvider;
	private String name;
	private String nameOwner;
	private String addr1;
	private String addr2;
	private String addrLoad1;
	private String addrLoad2;
	private Float latitude;
	private Float longitude;
	private String checkIn;
	private String checkOut;
	private String phone;
	private String mobileOwner;
	private String mobileManager;
	private Float addPriceAdult;
	private Float addPriceChild;
	private Float addPriceToddler;
	private String urlWebsite;
	private String descriptionTraffic1;
	private String descriptionTraffic2;
	private String description;
	private Character managementType;
	private Character reservationType;
	private Character state;
	private Date regDate;
	private Set<AccountPension> accountPensions = new HashSet<AccountPension>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<PensionTheme> pensionThemes = new HashSet<PensionTheme>(0);
	private Set<Room> rooms = new HashSet<Room>(0);
	private Set<Advertisement> advertisements = new HashSet<Advertisement>(0);
	private Set<PensionImage> pensionImages = new HashSet<PensionImage>(0);
	private Set<PensionFacility> pensionFacilities = new HashSet<PensionFacility>(0);
	private Set<PensionProvide> pensionProvides = new HashSet<PensionProvide>(0);
	private Set<RecommendationPension> recommendationPensions = new HashSet<RecommendationPension>(0);

	public Pension() {
	}

	public Pension(Area2 area2, Date regDate) {
		this.area2 = area2;
		this.regDate = regDate;
	}

	public Pension(Area2 area2, String idfProvider, String name, String nameOwner, String addr1, String addr2,
			String addrLoad1, String addrLoad2, Float latitude, Float longitude, String checkIn, String checkOut,
			String phone, String mobileOwner, String mobileManager, Float addPriceAdult, Float addPriceChild,
			Float addPriceToddler, String urlWebsite, String descriptionTraffic1, String descriptionTraffic2,
			String description, Character managementType, Character reservationType, Character state, Date regDate,
			Set<AccountPension> accountPensions, Set<Review> reviews, Set<PensionTheme> pensionThemes, Set<Room> rooms,
			Set<Advertisement> advertisements, Set<PensionImage> pensionImages, Set<PensionFacility> pensionFacilities,
			Set<PensionProvide> pensionProvides, Set<RecommendationPension> recommendationPensions) {
		this.area2 = area2;
		this.idfProvider = idfProvider;
		this.name = name;
		this.nameOwner = nameOwner;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addrLoad1 = addrLoad1;
		this.addrLoad2 = addrLoad2;
		this.latitude = latitude;
		this.longitude = longitude;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.phone = phone;
		this.mobileOwner = mobileOwner;
		this.mobileManager = mobileManager;
		this.addPriceAdult = addPriceAdult;
		this.addPriceChild = addPriceChild;
		this.addPriceToddler = addPriceToddler;
		this.urlWebsite = urlWebsite;
		this.descriptionTraffic1 = descriptionTraffic1;
		this.descriptionTraffic2 = descriptionTraffic2;
		this.description = description;
		this.managementType = managementType;
		this.reservationType = reservationType;
		this.state = state;
		this.regDate = regDate;
		this.accountPensions = accountPensions;
		this.reviews = reviews;
		this.pensionThemes = pensionThemes;
		this.rooms = rooms;
		this.advertisements = advertisements;
		this.pensionImages = pensionImages;
		this.pensionFacilities = pensionFacilities;
		this.pensionProvides = pensionProvides;
		this.recommendationPensions = recommendationPensions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_pension", unique = true, nullable = false)
	public Integer getIdfPension() {
		return this.idfPension;
	}

	public void setIdfPension(Integer idfPension) {
		this.idfPension = idfPension;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_area2", nullable = false)
	public Area2 getArea2() {
		return this.area2;
	}

	public void setArea2(Area2 area2) {
		this.area2 = area2;
	}
	
	@Column(name = "idf_provider", length = 10)
	public String getIdfProvider() {
		return this.idfProvider;
	}

	public void setIdfProvider(String idfProvider) {
		this.idfProvider = idfProvider;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_owner", length = 100)
	public String getNameOwner() {
		return this.nameOwner;
	}

	public void setNameOwner(String nameOwner) {
		this.nameOwner = nameOwner;
	}

	@Column(name = "addr1", length = 300)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "addr2", length = 45)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "addr_load1", length = 300)
	public String getAddrLoad1() {
		return this.addrLoad1;
	}

	public void setAddrLoad1(String addrLoad1) {
		this.addrLoad1 = addrLoad1;
	}

	@Column(name = "addr_load2", length = 45)
	public String getAddrLoad2() {
		return this.addrLoad2;
	}

	public void setAddrLoad2(String addrLoad2) {
		this.addrLoad2 = addrLoad2;
	}

	@Column(name = "latitude", precision = 10, scale = 6)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 10, scale = 6)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "check_in", length = 2)
	public String getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(String checkIn) {
		this.checkIn = checkIn;
	}

	@Column(name = "check_out", length = 2)
	public String getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(String checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "phone", length = 13)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mobile_owner", length = 13)
	public String getMobileOwner() {
		return this.mobileOwner;
	}

	public void setMobileOwner(String mobileOwner) {
		this.mobileOwner = mobileOwner;
	}

	@Column(name = "mobile_manager", length = 13)
	public String getMobileManager() {
		return this.mobileManager;
	}

	public void setMobileManager(String mobileManager) {
		this.mobileManager = mobileManager;
	}

	@Column(name = "add_price_adult", precision = 12, scale = 0)
	public Float getAddPriceAdult() {
		return this.addPriceAdult;
	}

	public void setAddPriceAdult(Float addPriceAdult) {
		this.addPriceAdult = addPriceAdult;
	}

	@Column(name = "add_price_child", precision = 12, scale = 0)
	public Float getAddPriceChild() {
		return this.addPriceChild;
	}

	public void setAddPriceChild(Float addPriceChild) {
		this.addPriceChild = addPriceChild;
	}

	@Column(name = "add_price_toddler", precision = 12, scale = 0)
	public Float getAddPriceToddler() {
		return this.addPriceToddler;
	}

	public void setAddPriceToddler(Float addPriceToddler) {
		this.addPriceToddler = addPriceToddler;
	}

	@Column(name = "url_website", length = 500)
	public String getUrlWebsite() {
		return this.urlWebsite;
	}

	public void setUrlWebsite(String urlWebsite) {
		this.urlWebsite = urlWebsite;
	}

	@Column(name = "description_traffic1", length = 65535)
	public String getDescriptionTraffic1() {
		return this.descriptionTraffic1;
	}

	public void setDescriptionTraffic1(String descriptionTraffic1) {
		this.descriptionTraffic1 = descriptionTraffic1;
	}

	@Column(name = "description_traffic2", length = 65535)
	public String getDescriptionTraffic2() {
		return this.descriptionTraffic2;
	}

	public void setDescriptionTraffic2(String descriptionTraffic2) {
		this.descriptionTraffic2 = descriptionTraffic2;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "management_type", length = 1)
	public Character getManagementType() {
		return this.managementType;
	}

	public void setManagementType(Character managementType) {
		this.managementType = managementType;
	}
	
	@Column(name = "reservation_type", length = 1)
	public Character getReservationType() {
		return this.reservationType;
	}

	public void setReservationType(Character reservationType) {
		this.reservationType = reservationType;
	}
	

	@Column(name = "state", length = 1)
	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<AccountPension> getAccountPensions() {
		return this.accountPensions;
	}

	public void setAccountPensions(Set<AccountPension> accountPensions) {
		this.accountPensions = accountPensions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<PensionTheme> getPensionThemes() {
		return this.pensionThemes;
	}

	public void setPensionThemes(Set<PensionTheme> pensionThemes) {
		this.pensionThemes = pensionThemes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<Advertisement> getAdvertisements() {
		return this.advertisements;
	}

	public void setAdvertisements(Set<Advertisement> advertisements) {
		this.advertisements = advertisements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<PensionImage> getPensionImages() {
		return this.pensionImages;
	}

	public void setPensionImages(Set<PensionImage> pensionImages) {
		this.pensionImages = pensionImages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<PensionFacility> getPensionFacilities() {
		return this.pensionFacilities;
	}

	public void setPensionFacilities(Set<PensionFacility> pensionFacilities) {
		this.pensionFacilities = pensionFacilities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<PensionProvide> getPensionProvides() {
		return this.pensionProvides;
	}

	public void setPensionProvides(Set<PensionProvide> pensionProvides) {
		this.pensionProvides = pensionProvides;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pension")
	public Set<RecommendationPension> getRecommendationPensions() {
		return this.recommendationPensions;
	}

	public void setRecommendationPensions(Set<RecommendationPension> recommendationPensions) {
		this.recommendationPensions = recommendationPensions;
	}

}
