package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Provide generated by hbm2java
 */
@Entity
@Table(name = "provide", catalog = "PensionRun")
public class Provide implements java.io.Serializable {

	private Integer idfProvide;
	private String name;
	private Byte priority;
	private Date regDate;
	private Set<PensionProvide> pensionProvides = new HashSet<PensionProvide>(0);

	public Provide() {
	}

	public Provide(String name, Date regDate) {
		this.name = name;
		this.regDate = regDate;
	}

	public Provide(String name, Byte priority, Date regDate, Set<PensionProvide> pensionProvides) {
		this.name = name;
		this.priority = priority;
		this.regDate = regDate;
		this.pensionProvides = pensionProvides;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_provide", unique = true, nullable = false)
	public Integer getIdfProvide() {
		return this.idfProvide;
	}

	public void setIdfProvide(Integer idfProvide) {
		this.idfProvide = idfProvide;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provide")
	public Set<PensionProvide> getPensionProvides() {
		return this.pensionProvides;
	}

	public void setPensionProvides(Set<PensionProvide> pensionProvides) {
		this.pensionProvides = pensionProvides;
	}

}
