package com.pensionrun.entity;
// Generated 2016. 4. 29 오후 9:11:17 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recommendation generated by hbm2java
 */
@Entity
@Table(name = "recommendation", catalog = "PensionRun")
public class Recommendation implements java.io.Serializable {

	private int idfRecommendation;
	private String title;
	private String titleSub;
	private String image;
	private Byte priority;
	private Date regDate;
	private Set<RecommendationPension> recommendationPensions = new HashSet<RecommendationPension>(0);

	public Recommendation() {
	}

	public Recommendation(int idfRecommendation, String title, String titleSub, String image, Date regDate) {
		this.idfRecommendation = idfRecommendation;
		this.title = title;
		this.titleSub = titleSub;
		this.image = image;
		this.regDate = regDate;
	}

	public Recommendation(int idfRecommendation, String title, String titleSub, String image, Byte priority,
			Date regDate, Set<RecommendationPension> recommendationPensions) {
		this.idfRecommendation = idfRecommendation;
		this.title = title;
		this.titleSub = titleSub;
		this.image = image;
		this.priority = priority;
		this.regDate = regDate;
		this.recommendationPensions = recommendationPensions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idf_recommendation", unique = true, nullable = false)
	public int getIdfRecommendation() {
		return this.idfRecommendation;
	}

	public void setIdfRecommendation(int idfRecommendation) {
		this.idfRecommendation = idfRecommendation;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "title_sub", nullable = false, length = 45)
	public String getTitleSub() {
		return this.titleSub;
	}

	public void setTitleSub(String titleSub) {
		this.titleSub = titleSub;
	}

	@Column(name = "image", nullable = false, length = 500)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recommendation")
	public Set<RecommendationPension> getRecommendationPensions() {
		return this.recommendationPensions;
	}

	public void setRecommendationPensions(Set<RecommendationPension> recommendationPensions) {
		this.recommendationPensions = recommendationPensions;
	}

}
