package com.pensionrun.entity;
// Generated 2016. 4. 29 오후 9:11:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PensionRecommendation generated by hbm2java
 */
@Entity
@Table(name = "recommendation_pension", catalog = "PensionRun")
public class RecommendationPension implements java.io.Serializable {

	private RecommendationPensionId id;
	private Pension pension;
	private Recommendation recommendation;
	private Date regDate;

	public RecommendationPension() {
	}

	public RecommendationPension(RecommendationPensionId id, Pension pension, Recommendation recommendation, Date regDate) {
		this.id = id;
		this.pension = pension;
		this.recommendation = recommendation;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idfRecommendation", column = @Column(name = "idf_recommendation", nullable = false)),
			@AttributeOverride(name = "idfPension", column = @Column(name = "idf_pension", nullable = false)) })
	public RecommendationPensionId getId() {
		return this.id;
	}

	public void setId(RecommendationPensionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_pension", nullable = false, insertable = false, updatable = false)
	public Pension getPension() {
		return this.pension;
	}

	public void setPension(Pension pension) {
		this.pension = pension;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_recommendation", nullable = false, insertable = false, updatable = false)
	public Recommendation getRecommendation() {
		return this.recommendation;
	}

	public void setRecommendation(Recommendation recommendation) {
		this.recommendation = recommendation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
