package com.pensionrun.entity;
// Generated 2016. 5. 19 오후 11:24:48 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReviewImage generated by hbm2java
 */
@Entity
@Table(name = "review_image", catalog = "PensionRun")
public class ReviewImage implements java.io.Serializable {

	private Integer idfReviewImage;
	private Review review;
	private String image;
	private byte priority;
	private Date regDate;

	public ReviewImage() {
	}

	public ReviewImage(Review review, String image, byte priority, Date regDate) {
		this.review = review;
		this.image = image;
		this.priority = priority;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_review_image", unique = true, nullable = false)
	public Integer getIdfReviewImage() {
		return this.idfReviewImage;
	}

	public void setIdfReviewImage(Integer idfReviewImage) {
		this.idfReviewImage = idfReviewImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_review", nullable = false)
	public Review getReview() {
		return this.review;
	}

	public void setReview(Review review) {
		this.review = review;
	}

	@Column(name = "image", nullable = false, length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "priority", nullable = false)
	public byte getPriority() {
		return this.priority;
	}

	public void setPriority(byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
