package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoomAmenityId generated by hbm2java
 */
@Embeddable
public class RoomAmenityId implements java.io.Serializable {

	private int idfRoom;
	private int idfAmenity;

	public RoomAmenityId() {
	}

	public RoomAmenityId(int idfRoom, int idfAmenity) {
		this.idfRoom = idfRoom;
		this.idfAmenity = idfAmenity;
	}

	@Column(name = "idf_room", nullable = false)
	public int getIdfRoom() {
		return this.idfRoom;
	}

	public void setIdfRoom(int idfRoom) {
		this.idfRoom = idfRoom;
	}

	@Column(name = "idf_amenity", nullable = false)
	public int getIdfAmenity() {
		return this.idfAmenity;
	}

	public void setIdfAmenity(int idfAmenity) {
		this.idfAmenity = idfAmenity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoomAmenityId))
			return false;
		RoomAmenityId castOther = (RoomAmenityId) other;

		return (this.getIdfRoom() == castOther.getIdfRoom()) && (this.getIdfAmenity() == castOther.getIdfAmenity());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfRoom();
		result = 37 * result + this.getIdfAmenity();
		return result;
	}

}
