package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoomPriceId generated by hbm2java
 */
@Embeddable
public class RoomPriceId implements java.io.Serializable {

	private int idfRoom;
	private String checkDate;

	public RoomPriceId() {
	}

	public RoomPriceId(int idfRoom, String checkDate) {
		this.idfRoom = idfRoom;
		this.checkDate = checkDate;
	}

	@Column(name = "idf_room", nullable = false)
	public int getIdfRoom() {
		return this.idfRoom;
	}

	public void setIdfRoom(int idfRoom) {
		this.idfRoom = idfRoom;
	}

	@Column(name = "check_date", nullable = false, length = 10)
	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoomPriceId))
			return false;
		RoomPriceId castOther = (RoomPriceId) other;

		return (this.getIdfRoom() == castOther.getIdfRoom()) && ((this.getCheckDate() == castOther.getCheckDate())
				|| (this.getCheckDate() != null && castOther.getCheckDate() != null
						&& this.getCheckDate().equals(castOther.getCheckDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfRoom();
		result = 37 * result + (getCheckDate() == null ? 0 : this.getCheckDate().hashCode());
		return result;
	}

}
