package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoomImage generated by hbm2java
 */
@Entity
@Table(name = "room_image", catalog = "PensionRun")
public class RoomImage implements java.io.Serializable {

	private Integer idfRoomImage;
	private Room room;
	private String image;
	private Byte priority;
	private Date regDate;

	public RoomImage() {
	}

	public RoomImage(Room room) {
		this.room = room;
	}

	public RoomImage(Room room, String image, Byte priority, Date regDate) {
		this.room = room;
		this.image = image;
		this.priority = priority;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_room_image", unique = true, nullable = false)
	public Integer getIdfRoomImage() {
		return this.idfRoomImage;
	}

	public void setIdfRoomImage(Integer idfRoomImage) {
		this.idfRoomImage = idfRoomImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_room", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
