package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoomPrice generated by hbm2java
 */
@Entity
@Table(name = "room_price", catalog = "PensionRun")
public class RoomPrice implements java.io.Serializable {

	private RoomPriceId id;
	private Room room;
	private Character type;
	private Float price;
	private Float priceDiscount;
	private byte remainRoomCount;
	
	private Date regDate;

	public RoomPrice() {
	}

	public RoomPrice(RoomPriceId id, Room room, Character type, Float price, Float priceDiscount, byte remainRoomCount, Date regDate) {
		this.id = id;
		this.room = room;
		this.type = type;
		this.price = price;
		this.priceDiscount = priceDiscount;
		this.remainRoomCount = remainRoomCount;
		
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idfRoom", column = @Column(name = "idf_room", nullable = false)),
			@AttributeOverride(name = "checkDate", column = @Column(name = "check_date", nullable = false, length = 10)) })
	public RoomPriceId getId() {
		return this.id;
	}

	public void setId(RoomPriceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_room", nullable = false, insertable = false, updatable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "price_discount", precision = 12, scale = 0)
	public Float getPriceDiscount() {
		return this.priceDiscount;
	}

	public void setPriceDiscount(Float priceDiscount) {
		this.priceDiscount = priceDiscount;
	}
	
	@Column(name = "remain_room_count", nullable = false)
	public byte getRemainRoomCount() {
		return this.remainRoomCount;
	}

	public void setRemainRoomCount(byte remainRoomCount) {
		this.remainRoomCount = remainRoomCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", length = 19, insertable=false, updatable=false)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
