package com.pensionrun.entity;
// Generated 2016. 4. 27 오전 12:18:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "theme", catalog = "PensionRun")
public class Theme implements java.io.Serializable {

	private Integer idfTheme;
	private String name;
	private Byte priority;
	private Date regDate;
	private Set<PensionTheme> pensionThemes = new HashSet<PensionTheme>(0);

	public Theme() {
	}

	public Theme(String name, Date regDate) {
		this.name = name;
		this.regDate = regDate;
	}

	public Theme(String name, Byte priority, Date regDate, Set<PensionTheme> pensionThemes) {
		this.name = name;
		this.priority = priority;
		this.regDate = regDate;
		this.pensionThemes = pensionThemes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idf_theme", unique = true, nullable = false)
	public Integer getIdfTheme() {
		return this.idfTheme;
	}

	public void setIdfTheme(Integer idfTheme) {
		this.idfTheme = idfTheme;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority")
	public Byte getPriority() {
		return this.priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theme")
	public Set<PensionTheme> getPensionThemes() {
		return this.pensionThemes;
	}

	public void setPensionThemes(Set<PensionTheme> pensionThemes) {
		this.pensionThemes = pensionThemes;
	}

}
